project:
  type: website
  output-dir: docs

website:
  title: "OceaniaR Hackathon 2024"
  navbar:
   left:
    - text: " "
      href: index.qmd
   tools:
      - icon: github
        menu:
          - text: Report a Bug
            href:  https://github.com/StatSocAus/oceaniaR-hack/issues
  page-footer: "Please see the attached [Code of Conduct](https://github.com/StatSocAus/oceaniaR-hack/blob/main/CODEOFCONDUCT.md)." 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



